import '@fontsource/barlow-condensed/latin-600.css';
import '@fontsource/ibm-plex-mono/latin-400.css';
import './style.css';
import { products } from './products.js';

const repo = 'https://github.com/HarzerHeribert/glasshouse';
const product = document.title.startsWith('Pane —') ? 'pane' : document.title.startsWith('Glasshouse —') ? 'glasshouse' : null;
const root = product ? '../' : './';
const arrow = '<span aria-hidden="true">↗</span>';
const mark = '<svg viewBox="0 0 38 38" aria-hidden="true"><path d="M5 9h22v24H5zM12 3h22v24H12z"/></svg>';
const scene = (kind, className = '') => `<div class="optics ${className}" data-scene="${kind}" data-root="${root}" aria-hidden="true"><div class="optics-fallback ${kind === 'house' ? 'house-fallback' : 'specimen-fallback'}">${kind === 'house' ? '<span>GLASS<br>HOUSE</span>' : `<img src="${root}specimens.png" alt="" loading="lazy"/>`}</div><canvas></canvas></div>`;
const button = (text, href, dark = false) => `<a class="button ${dark ? 'dark' : ''}" href="${href}">${text} ${arrow}</a>`;
const list = (key, count = 6) => `<div class="feature-list">${products[key].features.slice(0,count).map(([name,copy,status])=>`<article><h3>${name}</h3><p>${copy}</p>${status ? `<span class="feature-status">${status}</span>` : ''}</article>`).join('')}</div>`;
const compare = (c) => `<section class="section compare"><div class="program"><pre>${c.diagram}</pre><div><h2>${c.title}</h2><p>${c.body}</p></div></div></section>`;
const nav = `<a class="skip" href="#main">Skip to content</a><header><a class="wordmark" href="${root}" aria-label="Glasshouse home">${mark}<span>GLASSHOUSE</span></a><nav aria-label="Main navigation"><a href="${root}glasshouse/" ${product === 'glasshouse' ? 'aria-current="page"' : ''}>Orchestrator</a><a href="${root}pane/" ${product === 'pane' ? 'aria-current="page"' : ''}>Harness</a><a class="source-link" href="${repo}">Source ${arrow}</a></nav></header>`;
const motion = '<button class="motion-toggle" type="button" aria-pressed="false">Pause motion</button>';
const home = `<section class="hero"><div class="eyebrow"><span class="status-dot"></span> OPEN SOURCE. IN DEVELOPMENT.</div><h1>NOTHING<br>TO <span class="outline">HIDE.</span></h1>${scene('house')}<div class="hero-bottom"><p>Every session in view.<br>Every agent within reach.</p><a class="text-link" href="#products">Meet Glasshouse & Pane <span aria-hidden="true">↓</span></a></div></section><section class="name-story section"><h2>THAT’S WHY IT’S<br>CALLED GLASSHOUSE.</h2><p>Your agents work in the open. See every session, follow the work, and step in whenever you need to. Glasshouse keeps the user in control.</p></section>
<section id="products" class="products section"><div class="product-intro"><h2>TWO TOOLS.<br>ONE OPEN SYSTEM.</h2><p>Glasshouse coordinates the agents.<br>Pane is an agent you work with.</p></div>${['glasshouse','pane'].map(key=>`<section class="product-block"><div class="product-heading"><div><div class="eyebrow">${products[key].role}</div><h2>${products[key].name}</h2></div><p>${products[key].description}</p></div><div class="product-content">${scene(key === 'glasshouse' ? 'seed' : 'shell','inline-optics')}${list(key,3)}</div>${button(products[key].action,`${root}${key}/`,key==='pane')}<a class="all-features" href="${root}${key}/#features">All features ${arrow}</a></section>`).join('')}</section>
<section class="relationship section"><div class="relationship-copy"><h2>WORK TOGETHER.<br>STAND APART.</h2><p>Glasshouse coordinates Pane alongside your other installed harnesses. Pane can also run on its own. Choose the layer you need.</p></div><div class="system-map" aria-label="Glasshouse coordinates Pane, Claude Code, Codex, and OpenCode"><div class="map-parent">${mark} GLASSHOUSE <span>COORDINATION / ROUTING / PROJECT MEMORY</span></div><div class="map-children"><a href="${root}pane/">PANE <span>OUR HARNESS ↗</span></a><span>CLAUDE CODE</span><span>CODEX</span><span>OPENCODE</span></div></div></section>`;
const data = products[product || 'glasshouse'];
const detail = `<section class="hero detail-hero"><div class="eyebrow"><span class="status-dot"></span> ${data.role}</div><h1>${data.title}</h1>${scene(product === 'pane' ? 'shell' : 'house')}<div class="hero-bottom"><p>${data.intro}</p>${button(data.action,'#get')}</div></section>${data.compare ? compare(data.compare) : ''}<section id="features" class="section detail-section"><div class="relationship-copy"><h2>${product === 'pane' ? 'GIVE REASONING<br>ROOM TO RUN.' : 'COORDINATE.<br>STAY IN CONTROL.'}</h2><p>${data.description}</p></div><p class="development-note">${data.status}</p>${list(product || 'glasshouse')}</section><section class="specimen-story section"><div><h2>${product === 'pane' ? 'KEEP THE WORK.<br>MOVE THE THINKING.' : 'LET THE WORK<br>FIND ITS WAY.'}</h2><p>${product === 'pane' ? 'A result can stay in the runtime while the model works on what it means. Pane’s intended object model makes that separation explicit.' : 'Each session brings its own context and capabilities. Glasshouse gives the orchestrator a view across them, so it can choose where the next task belongs.'}</p></div>${scene(product === 'pane' ? 'shell' : 'seed','inline-optics')}</section><section id="get" class="get-section section"><h2>${data.action.toUpperCase()}.</h2><p>${product === 'pane' ? 'Explore the Pane source and its implementation milestones. The code execution path remains gated on the sandbox requirements.' : 'Build Glasshouse from source, then bring your installed coding harnesses. Find setup instructions and current limitations in the repository.'}</p>${button(data.cta,data.link,true)}<a class="text-link roadmap" href="${repo}/blob/main/docs/product/capability-map.md">Implementation status ${arrow}</a></section><aside class="other-product"><span>${product === 'pane' ? 'Need to coordinate several agents?' : 'Looking for the harness itself?'}</span><a href="${root}${product === 'pane' ? 'glasshouse' : 'pane'}/">Meet ${product === 'pane' ? 'Glasshouse' : 'Pane'} ${arrow}</a></aside>`;
document.querySelector('#app').innerHTML = `${nav}<main id="main">${product ? detail : home}</main><footer><a class="wordmark" href="${root}">${mark}<span>GLASSHOUSE</span></a>${motion}<a href="${repo}">GitHub ${arrow}</a></footer>`;
import('./optics.js').then(({startOptics})=>startOptics([...document.querySelectorAll('.optics')],document.querySelector('.motion-toggle'))).catch(()=>{document.querySelector('.motion-toggle').hidden=true;});
