#!/usr/bin/env python3
"""Catch capability-ID drift the moment it happens, instead of retroactively.

WHY THIS EXISTS
---------------
**A capability's ID is literally its line number in `capability-map.md`.** "1641"
means "line 1641". There are no stable identifiers, anywhere.

That works right up until somebody inserts a mandatory capability mid-map. The
moment they do, **every ID below the insertion silently means something else** —
every evidence citation, every packet quote, every practice reference, every
historical handoff, and the `--lines` flag of `new-packet.sh`. Nothing crashes.
The numbers still resolve. They just resolve to the wrong capability.

Checked before writing this: only two commits have ever inserted map lines
without deleting any, and **both landed below line 1978 (1943 before Phases 56/56A were inserted on 2026-08-31)**, inside the
"Maybe / Experimental" section. So the mandatory range has never actually
shifted. That is luck, not design — the insertions happened to be at the bottom.

What already existed:
  * `check-evidence-coverage.py` indexes boxes by TEXT, so it is drift-immune.
  * `validate_round.py` compares a packet's quoted text against the line it
    cites — real detection, but only at dispatch, and that check was itself dead
    for at least four rounds (it matched only lines whose FIRST character is a
    box glyph, while every packet writes `- **1311** ☐ …`).

What did not exist, and is what this adds: anything that notices the map itself
moved. This is a canary, not a fix. The fix is stable IDs, which is a migration
touching every evidence file and every packet.

TICKING A BOX IS NOT DRIFT. `☐` → `☑` changes the line in place and must stay
silent, or the check cries wolf on the single most common map edit there is and
gets ignored — which is how this project has lost gates before.

USAGE
    scripts/map-index.py --update    # after a DELIBERATE map change
    scripts/map-index.py --check     # in the gate; exit 1 on drift
"""
from __future__ import annotations

import argparse
import hashlib
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAP = os.path.join(REPO, "docs/product/capability-map.md")
INDEX = os.path.join(REPO, "docs/product/capability-map.index")

# How far to look for a line that moved before giving up and calling it a
# rewrite rather than a shift. Generous: a whole phase can be inserted at once.
SEARCH = 400


def normalise(line: str) -> str:
    """A box line's identity, ignoring whether it is ticked.

    Stripping the glyph is the whole reason this check is usable: ticking a box
    is the most common edit the map ever receives, and a canary that fires on it
    would be silenced within a day.
    """
    s = line.strip()
    if s[:1] in ("☐", "☑"):
        s = s[1:].strip()
    return " ".join(s.split())


def boxes(path: str) -> dict[int, str]:
    out: dict[int, str] = {}
    with open(path, encoding="utf-8") as fh:
        for n, line in enumerate(fh.read().split("\n"), start=1):
            if line[:1] in ("☐", "☑"):
                out[n] = normalise(line)
    return out


def digest(text: str) -> str:
    return hashlib.sha1(text.encode("utf-8")).hexdigest()[:16]


def write_index(current: dict[int, str]) -> None:
    lines = [
        "# capability-map ID index — generated by scripts/map-index.py",
        "# <line>\t<sha1-16 of the box text, ignoring the tick glyph>",
        "# A capability's ID is its line number. This file is what notices when",
        "# a line number stops meaning what it meant.",
    ]
    for n in sorted(current):
        lines.append(f"{n}\t{digest(current[n])}")
    with open(INDEX, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


def read_index() -> dict[int, str]:
    out: dict[int, str] = {}
    with open(INDEX, encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("#") or not line.strip():
                continue
            n, h = line.split("\t")
            out[int(n)] = h.strip()
    return out


def check() -> int:
    if not os.path.exists(INDEX):
        print("map-index: no index yet — run scripts/map-index.py --update")
        return 1
    recorded = read_index()
    current = boxes(MAP)
    current_digests = {n: digest(t) for n, t in current.items()}

    moved: list[tuple[int, int]] = []   # (was, now)
    gone: list[int] = []
    for n, h in sorted(recorded.items()):
        if current_digests.get(n) == h:
            continue
        # Did this exact capability move? Search near, then wide.
        found = None
        for delta in range(1, SEARCH + 1):
            for cand in (n + delta, n - delta):
                if current_digests.get(cand) == h:
                    found = cand
                    break
            if found:
                break
        (moved.append((n, found)) if found else gone.append(n))

    added = sorted(set(current) - set(recorded))

    if not moved and not gone:
        extra = f", {len(added)} new box(es) appended" if added else ""
        print(f"map-index: {len(recorded)} capability IDs stable{extra}")
        if added:
            print("           run --update to record them")
        return 0

    print("map-index: CAPABILITY IDS HAVE DRIFTED — this is not cosmetic.")
    print()
    if moved:
        # Report the shift, not a thousand individual lines. The actionable fact
        # is "everything below X moved by N", which names the insertion point.
        shifts: dict[int, int] = {}
        for was, now in moved:
            shifts.setdefault(now - was, 0)
            shifts[now - was] += 1
        first = min(w for w, _ in moved)
        print(f"  {len(moved)} capability line(s) moved. Earliest affected ID: {first}")
        for delta, count in sorted(shifts.items()):
            print(f"    {count:>4} ID(s) shifted by {delta:+d}")
        print()
        print(f"  EVERY reference to an ID at or below {first} now names a different")
        print("  capability: evidence citations, packet quotes, practice references,")
        print("  past handoffs, and new-packet.sh --lines.")
    if gone:
        print(f"  {len(gone)} recorded capability line(s) no longer exist anywhere:")
        for n in gone[:10]:
            print(f"    line {n}")
        if len(gone) > 10:
            print(f"    ... and {len(gone) - 10} more")
    print()
    print("  If the map edit was deliberate, the numbers must be reconciled BEFORE")
    print("  --update, or the index will simply bless the drift. If it was not,")
    print("  revert it: appending below the experimental section shifts nothing.")
    return 1


def main() -> int:
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--update", action="store_true")
    g.add_argument("--check", action="store_true")
    args = ap.parse_args()
    if args.update:
        current = boxes(MAP)
        write_index(current)
        print(f"map-index: recorded {len(current)} capability IDs")
        return 0
    return check()


if __name__ == "__main__":
    raise SystemExit(main())
