#!/usr/bin/env python3
"""Turn an a2sg `ascii-dom` document into the frame bank the TUI embeds.

a2sg emits one self-contained HTML file whose payload is a JSON object with a
`text` array - one string per frame, rows joined by newline. Nothing else in
that file is wanted here: the player, the CSS and the per-cell colours are for a
web page, and the TUI supplies colour from the active theme instead.

Usage: pack.py <ascii-dom.html> <out.frames> [--interval MS]
"""
import json
import pathlib
import re
import sys

SEP = "%"


def main() -> int:
    argv = sys.argv[1:]
    interval = 80
    args = []
    i = 0
    while i < len(argv):
        a = argv[i]
        if a == "--interval":
            interval = int(argv[i + 1])
            i += 2
        elif a.startswith("--interval="):
            interval = int(a.split("=", 1)[1])
            i += 1
        else:
            args.append(a)
            i += 1
    src, dst = pathlib.Path(args[0]), pathlib.Path(args[1])

    doc = src.read_text()
    m = re.search(r'<script type="application/json">(.*?)</script>', doc, re.S)
    if not m:
        print("no ascii-dom payload in that document", file=sys.stderr)
        return 1
    payload = json.loads(m.group(1).replace("\\u003c", "<").replace("\\u0027", "'"))

    cols, rows = payload["cols"], payload["rows"]
    frames = [f.split("\n") for f in payload["text"]]
    for i, f in enumerate(frames):
        if len(f) != rows or any(len(line) != cols for line in f):
            print(f"frame {i} is not {cols}x{rows}", file=sys.stderr)
            return 1

    out = [
        "# Glasshouse startup animation - frame bank.",
        "# Generated by assets/startup/pack.py from assets/startup/glasshouse-scene.mjs.",
        "# Do not hand-edit: rebuild with assets/startup/build.sh.",
        "#",
        "# Lines are RIGHT-TRIMMED and padded back to `grid` columns on load, so a",
        "# whitespace-stripping editor cannot corrupt a frame. A frame is `@<index>`",
        "# followed by up to `rows` lines; missing trailing lines are blank rows.",
        "# Glyphs carry intensity, never colour - the three `tier` lines below map",
        "# each glyph to one of the terminal theme's three roles.",
        f"{SEP}GHSTART 1",
        f"{SEP}grid {cols} {rows}",
        f"{SEP}frames {len(frames)}",
        f"{SEP}interval {interval}",
        f"{SEP}loop cycle",
        # The ramp glyphs and the four contour glyphs are deliberately disjoint
        # sets (see build.sh), so each tier is one kind of mark: faint partial
        # coverage, structure, and the near frame plus the seed.
        f"{SEP}tier quiet  .:;",
        f"{SEP}tier soft   =+*-/|\\",
        f"{SEP}tier bright #%@",
    ]
    for i, f in enumerate(frames):
        out.append(f"@{i}")
        trimmed = [line.rstrip() for line in f]
        while trimmed and trimmed[-1] == "":
            trimmed.pop()
        out.extend(trimmed)

    text = "\n".join(out) + "\n"
    dst.write_text(text)
    print(
        f"{dst}: {len(frames)} frames, {cols}x{rows}, "
        f"{len(text.encode()):,} bytes ({len(text.encode()) / len(frames):.0f}/frame)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
